# Site settings
title: Anthony Ellis-Booth
email: aellisbooth312@gmail.com
url: https://aellisbooth.github.io/Cyber-Ellis-Booth
description: "Portfolio of cybersecurity work samples for a junior-level cyber security professional."
keywords: "cybersecurity, cyber, security, portfolio, tech"
skills: "Cybersecurity - Analyst - Ethical Hacker"
meta_author: Ellis-Booth Anthony 

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: 

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: EFD09E #80B3FF
  primary-rgb: "239,208,158" #"128,179,255"
  secondary: D4AA7D #FD6E8A
  secondary-dark: 272727 #A2122F

# Footer settings
footer:
  copyright: Anthony Ellis-Booth
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: www.linkedin.com/in/anthony-ellis-booth-21b336270/
  - title: github
    url: https://github.com/aellisbooth

# Email Address (make sure to include "mailto:" before your email!)
email:
  email-url: mailto:aellisbooth312@gmail.com

# Postal address (add as many lines as necessary)
location:
  - line: Portage, Indiana

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.
Cyber icons created by <a href="https://www.flaticon.com/free-icons/cyber-attack" title="cyber attack icons">Freepik - Flaticon</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
